### ISSUE TITLE
coverage report from tests in travis does not get uploaded to codecov

### ISSUE THREAD

**Issue by aguang** [compbiocore/qcdb#19]
Although the tests get run in travis successfully, the coverage report does not get uploaded to codecov. The output of `docker-compose run coverage` is below:

1.29s$ docker-compose run coverage
Building coverage
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

**Comment by mcmcgrath13** [comment]
I think @fernandogelin mentioned to me that he was planning to fix this - something to do with docker
