### ISSUE TITLE
sra_metadata as standalone function that creates `metadata.yaml` sheet

### ISSUE THREAD

**Issue by aguang** [compbiocore/qcdb#47]
See #41 for some context.

We want to split out `sra_metadata.py` so that it actually is a standalone python script that will create a `metadata.yaml` sheet from querying SRA, for `qcdb.db_load` to parse and load. It will take as input a path to a data folder, and an output path where `metadata.yaml` will go. The data folder should have either `SRR` ids as generated from `sra-tools`/`fasts-dump`, or `SRX_SRS` ids as generated from `bioflows`.

**Comment by aguang** [comment]
For a sheet that's based on data from SRA, `db_id` should be filled out as an `SRS_SRX` id, and it should also have fields `sample_id`: `SRS` and `experiment_id`: `SRX`.

**Comment by j-stat** [comment]
All set and pushed to GitHub
