### ISSUE TITLE
fastQCparser

### ISSUE THREAD

**Issue by JRWallace** [compbiocore/qcdb#5]
Account for all use cases -- there are situations where some of the fastQC modules won't be populated with data. For example, if there are no adapters found, populate the database entry with a "no adapters found" message or something like that in a "flag" column.

**Comment by aguang** [comment]
To do this, add a column to these modules that is `FLAG` column with either PASS or NOPASS. If PASS then skip (and note that sample passed) in output, if NOPASS then output rest of columns

**Comment by aguang** [comment]
In new JSON format (see #8 ), will be a JSON cell we add

**Comment by aguang** [comment]
@ashokrags with the JSON format we've moved to, this means that when the fastqc module is not populated with data we actually end up with an empty JSON. Presumably this would not make it into the final comparison anyway. Additionally a warning can be added later for no data. Is this a suitable solution?
