### ISSUE TITLE
sometime in the future: sqlalchemy connections?

### ISSUE THREAD

**Issue by JRWallace** [compbiocore/qcdb#7]
sqlalchemy needs a persistent connection -- is this an issue? We might need to maintain a pool of connections so that several users can query and use the database at the same time without slowing each other down. Do we want an implementation that allows for several concurrent connections?

**Comment by JRWallace** [comment]
Can sqlalchemy have several concurrent connections? If it does, we can continue w sqlalchemy -- if it doesn't, we need to find a new implementation.

**Comment by mcmcgrath13** [comment]
@JRWallace @aguang is this still an issue? The API pools connections to the DB, I don't think this is an issue if two people are running QCDB locally

**Comment by aguang** [comment]
@mcmcgrath13 if you don't think it's an issue with the way the API is set up then yeah we can close
